import { Level, Routine, StepType } from "./domain/routine";

export const ROUTINES: Routine[] = [
    {
      id: 'beginner',
      name: 'Arranque',
      level: Level.beginner,
      duration: '7 min',
      totalSeconds: 420,
      description: 'Tu primer HIIT. Movimientos básicos, descansos generosos. Ideal si llevas tiempo sin cardio.',
      color: '#CAFF33',
      exercises: 6,
      steps: [
        { name: 'Preparación', note: 'Respira hondo, activa el core', type: StepType.prep, dur: 10 },
        { name: 'Jumping Jacks', note: 'Brazos arriba, piernas abiertas — ritmo constante', type: StepType.work, dur: 40 },
        { name: 'Descanso', note: 'Respira por la nariz si puedes', type: StepType.rest, dur: 20 },
        { name: 'Mountain Climbers', note: 'Manos en el suelo, rodillas al pecho alternando', type: StepType.work, dur: 40 },
        { name: 'Descanso', note: 'Sacude las manos, no te quedes quieta del todo', type: StepType.rest, dur: 20 },
        { name: 'Squat Jumps', note: 'Baja fuerte, salta, aterriza suave', type: StepType.work, dur: 40 },
        { name: 'Descanso', note: 'Por la mitad — vas muy bien', type: StepType.rest, dur: 20 },
        { name: 'High Knees', note: 'Rodillas al cinturón, brazos bombeando', type: StepType.work, dur: 40 },
        { name: 'Descanso', note: 'Casi en el tramo final', type: StepType.rest, dur: 20 },
        { name: 'Burpees modificados', note: 'Sin salto si es necesario — baja, plancha, sube', type: StepType.work, dur: 40 },
        { name: 'Descanso', note: 'Un esfuerzo más', type: StepType.rest, dur: 20 },
        { name: 'Skipping en sitio', note: 'Sprint estático — deja todo aquí', type: StepType.work, dur: 40 },
        { name: 'Enfriamiento', note: 'Respira, camina en sitio. Lo conseguiste 🔥', type: StepType.prep, dur: 30 },
      ],
    },
    {
      id: 'intermediate',
      name: 'Ignición',
      level: Level.intermediate,
      duration: '12 min',
      totalSeconds: 720,
      description: 'El salto real. Más ejercicios, menos descanso. Diseñado para quien ya tiene base de fuerza.',
      color: '#33C9FF',
      exercises: 8,
      steps: [
        { name: 'Activación', note: 'Moviliza hombros, caderas y rodillas', type: StepType.prep, dur: 15 },
        { name: 'Jumping Jacks', note: 'Calentamos el sistema cardio — ritmo medio', type: StepType.work, dur: 45 },
        { name: 'Descanso', note: 'Respira', type: StepType.rest, dur: 15 },
        { name: 'Burpees completos', note: 'Salto al final incluido — explosive!', type: StepType.work, dur: 45 },
        { name: 'Descanso', note: 'Recupera frecuencia', type: StepType.rest, dur: 15 },
        { name: 'Squat Jumps', note: 'Profundidad total, salto máximo', type: StepType.work, dur: 45 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 15 },
        { name: 'Mountain Climbers', note: 'Rápido, core apretado, no pierdas la plancha', type: StepType.work, dur: 45 },
        { name: 'Descanso', note: 'Mitad del entreno', type: StepType.rest, dur: 15 },
        { name: 'Lunge Jumps', note: 'Alterna piernas con salto — controla el aterrizaje', type: StepType.work, dur: 45 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 15 },
        { name: 'Push-up to T', note: 'Flexión + rotación lateral con brazo al techo', type: StepType.work, dur: 45 },
        { name: 'Descanso', note: 'Dos más', type: StepType.rest, dur: 15 },
        { name: 'High Knees sprint', note: 'A tope, el más rápido que puedas', type: StepType.work, dur: 45 },
        { name: 'Descanso', note: 'Último esfuerzo', type: StepType.rest, dur: 15 },
        { name: 'Skipping + Boxeo', note: 'Skipping rápido con golpes de puño alternos', type: StepType.work, dur: 45 },
        { name: 'Enfriamiento', note: 'Dobla la cintura, respira profundo. Brutal. 💪', type: StepType.prep, dur: 45 },
      ],
    },
    {
      id: 'advanced',
      name: 'Incendio',
      level: Level.advanced,
      duration: '20 min',
      totalSeconds: 1200,
      description: 'Sin piedad. Tabata estructurado, 20s trabajo / 10s descanso × 4 rondas por bloque. Para cuando el intermedio se quede corto.',
      color: '#FF8C42',
      exercises: 10,
      steps: [
        { name: 'Activación', note: 'Foam rolling mental — enfoca la mente', type: StepType.prep, dur: 20 },
  
        // BLOQUE 1: Piernas
        { name: '— BLOQUE 1: PIERNAS —', note: 'Squat jumps + Lunge jumps', type: StepType.prep, dur: 5 },
        { name: 'Squat Jumps', note: 'Ronda 1/4 — máxima potencia', type: StepType.work, dur: 20 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 10 },
        { name: 'Squat Jumps', note: 'Ronda 2/4', type: StepType.work, dur: 20 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 10 },
        { name: 'Lunge Jumps', note: 'Ronda 3/4 — alterna piernas con explosión', type: StepType.work, dur: 20 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 10 },
        { name: 'Lunge Jumps', note: 'Ronda 4/4 — última de piernas', type: StepType.work, dur: 20 },
        { name: 'Recuperación', note: 'Camina, sacude las piernas', type: StepType.rest, dur: 20 },
  
        // BLOQUE 2: Core + Upper
        { name: '— BLOQUE 2: CORE + UPPER —', note: 'Mountain climbers + Burpees', type: StepType.prep, dur: 5 },
        { name: 'Mountain Climbers', note: 'Ronda 1/4 — hombros sobre muñecas, core duro', type: StepType.work, dur: 20 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 10 },
        { name: 'Mountain Climbers', note: 'Ronda 2/4', type: StepType.work, dur: 20 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 10 },
        { name: 'Burpees completos', note: 'Ronda 3/4 — salto con brazos arriba', type: StepType.work, dur: 20 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 10 },
        { name: 'Burpees completos', note: 'Ronda 4/4 — termina fuerte', type: StepType.work, dur: 20 },
        { name: 'Recuperación', note: 'Respira, manos en la nuca', type: StepType.rest, dur: 20 },
  
        // BLOQUE 3: Cardio puro
        { name: '— BLOQUE 3: CARDIO PURO —', note: 'High knees + Skipping', type: StepType.prep, dur: 5 },
        { name: 'High Knees sprint', note: 'Ronda 1/4 — máxima cadencia', type: StepType.work, dur: 20 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 10 },
        { name: 'High Knees sprint', note: 'Ronda 2/4', type: StepType.work, dur: 20 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 10 },
        { name: 'Skipping explosivo', note: 'Ronda 3/4 — pies de boxeador', type: StepType.work, dur: 20 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 10 },
        { name: 'Skipping explosivo', note: 'Ronda 4/4 — todo lo que te queda', type: StepType.work, dur: 20 },
        { name: 'Recuperación', note: 'Camina lento, baja la frecuencia', type: StepType.rest, dur: 20 },
  
        // BLOQUE FINAL: Full body
        { name: '— BLOQUE FINAL: FULL BODY —', note: 'Última ronda de gloria', type: StepType.prep, dur: 5 },
        { name: 'Bear Crawl', note: 'Rodillas a 2cm del suelo, avanza y retrocede', type: StepType.work, dur: 20 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 10 },
        { name: 'Bear Crawl', note: 'Ronda 2 — mantén la espalda plana', type: StepType.work, dur: 20 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 10 },
        { name: 'Burpees + Tuck Jump', note: 'Burpee + salto rodillas al pecho — JEFE FINAL', type: StepType.work, dur: 20 },
        { name: 'Descanso', note: '', type: StepType.rest, dur: 10 },
        { name: 'Burpees + Tuck Jump', note: 'ÚLTIMA serie. Vacía el tanque.', type: StepType.work, dur: 20 },
  
        { name: 'Enfriamiento', note: 'Lo conseguiste. Respira. Eres una bestia. 🔥', type: StepType.prep, dur: 60 },
      ],
    },
  ];
  